
CREATE TABLE IF NOT EXISTS categories (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(512),
    parent INT,
    account INT NOT NULL REFERENCES accounts(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) DEFAULT CHARACTER SET 'utf8mb4';
